"""Price Tracker Pro - Report generation module"""

import argparse
from datetime import datetime
from jinja2 import Template
from src.scraper import PriceScraper


REPORT_TEMPLATE = """
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>价格监控报告 - {{ date }}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; background: #f5f5f5; }
        h1 { color: #333; border-bottom: 2px solid #4CAF50; padding-bottom: 10px; }
        .card { background: white; border-radius: 8px; padding: 20px; margin: 16px 0; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #eee; }
        th { background: #f8f9fa; font-weight: 600; }
        .up { color: #e53935; }
        .down { color: #43A047; }
        .footer { text-align: center; color: #888; margin-top: 30px; font-size: 12px; }
    </style>
</head>
<body>
    <h1>📊 价格监控报告</h1>
    <p>生成时间: {{ date }}</p>

    {% for name, history in data.items() %}
    <div class="card">
        <h2>{{ name }}</h2>
        {% if history %}
        <table>
            <tr><th>时间</th><th>价格</th></tr>
            {% for price, captured_at in history %}
            <tr>
                <td>{{ captured_at[:16] }}</td>
                <td>¥{{ "%.2f"|format(price) }}</td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <p>暂无数据</p>
        {% endif %}
    </div>
    {% endfor %}

    <div class="footer">
        Generated by Price Tracker Pro | github.com/kaising-openclaw1/price-tracker-pro
    </div>
</body>
</html>
"""


def generate_report(output: str = "report.html"):
    """生成HTML价格报告"""
    scraper = PriceScraper()

    data = {}
    targets = scraper.config["targets"]

    for target in targets:
        history = scraper.get_history(target["name"])
        data[target["name"]] = history

    template = Template(REPORT_TEMPLATE)
    html = template.render(
        date=datetime.now().strftime("%Y-%m-%d %H:%M"),
        data=data,
    )

    with open(output, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"📄 报告已生成: {output}")


def main():
    parser = argparse.ArgumentParser(description="生成价格监控报告")
    parser.add_argument("--output", default="report.html", help="输出文件名")
    args = parser.parse_args()
    generate_report(args.output)


if __name__ == "__main__":
    main()
